### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by algellar** [keeganryan/flatter#7]

**Comment by keeganryan** [comment]
Thanks for the issue, I think the linker error was due to compiling against an out-of-date version of fplll. We require certain features, specifically doing single-threaded BKZ, that only appeared in recent versions. I'll leave this issue open for now in case others get an undefined reference error to `fplll::set_external_enumerator` and update the CMake scripts to give a clear error message if the wrong version of fplll is found.

**Comment by algellar** [comment]
> Thanks for the issue, I think the linker error was due to compiling against an out-of-date version of fplll. We require certain features, specifically doing single-threaded BKZ, that only appeared in recent versions. I'll leave this issue open for now in case others get an undefined reference error to `fplll::set_external_enumerator` and update the CMake scripts to give a clear error message if the wrong version of fplll is found.

Thank you so much for your response!  Later, I found out that the reason for the error was because I was compiling with the terminal enabled in juypterlab, but using the terminal in ubuntu to compile successfully.
